title: "March Madness 2025"
description: "Predicting College Basketball Games"
baseurl: "/march_madness_2025"
url: "https://alexmangiafico.github.io/march_madness_2025"



remote_theme: qwtel/hydejack
plugins:
  - jekyll-feed
  - jekyll-seo-tag

menu:
  - title: "Home"
    url: /
    
  - title: "---"  # Divider for visual separation

  - title: "Process"  # Section title (not a link)
    url: ""  # Empty URL makes it non-clickable
  - title: "Data Collection"
    url: /process/data-collection/
  - title: "Feature Engineering"
    url: /process/feature-engineering/

  - title: "---"  # Divider for visual separation

  - title: "Exploratory Data Analysis"
    url: ""  # Section title, non-clickable
  - title: "Visualizations"
    url: /eda/visualizations/
  - title: "Statistical Summaries"
    url: /eda/statistics/

  - title: "---"

  - title: "Results"
    url: ""
  - title: "Model Performance"
    url: /results/model-performance/
  - title: "Conclusions"
    url: /results/conclusions/
