title: "March Madness 2025"
description: "Predicting College Basketball Games"
baseurl: "/march_madness_2025"
url: "https://alexmangiafico.github.io/march_madness_2025"
show_related_posts: false
show_page_list: false
show_last_modified: false


remote_theme: qwtel/hydejack

plugins:
  - jekyll-feed
  - jekyll-seo-tag

menu:
  - title: "Home"
    url: /

  - title: "Introduction"
    url: /introduction/
    
  - title: "Useful Metrics"
    url: /useful_metrics/

  - title: "Creation/Prevention"
    url: /creation_prevention/

  - title: "Selecting a Model"
    url: /selecting_a_model/

  - title: "Results"
    url: /results/

  - title: "Performance"
    url: /performance/
