title: "March Madness 2025"
description: "Predicting College Basketball Games"
baseurl: "/march_madness_2025" # The subdirectory where the site is located
url: "https://alexmangiafico.github.io/march_madness_2025" # The main URL of your site

remote_theme: jekyll/hyde # Use the Jekyll Hyde theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Menu configuration
menu:
  home: "/"
  intro: "/"
  background: "/background/"
  outline: "/outline/"
  modeling:
    - "/basketball_stats_engineering/"
    - "/feature_engineering/"
    - "/modeling/"
  results:
    - "/backtesting/"
    - "/2025_predictions/"
  performance:
    - "/machine_learning_mania/"
