title: "March Madness 2025"
description: "Predicting College Basketball Games"
baseurl: "/march_madness_2025"
url: "https://alexmangiafico.github.io/march_madness_2025"
show_related_posts: false
show_page_list: false


remote_theme: hydecorp/hyde

plugins:
  - jekyll-feed
  - jekyll-seo-tag

menu:
  - title: "Home"
    url: /

  - title: "Introduction"
    url: /introduction/
    
  - title: "Modeling"
    url: /modeling/

  - title: "Results"
    url: /results/

  - title: "Performance"
    url: /performance/
