title: "March Madness 2025"
description: "Predicting College Basketball Games"
baseurl: "/march_madness_2025"
url: "https://alexmangiafico.github.io/march_madness_2025"



remote_theme: qwtel/hydejack
plugins:
  - jekyll-feed
  - jekyll-seo-tag

menu:
  - title: "Home"
    url: /

  - title: "Introduction"
  - title: "Background"
    url: /background/
  - title: "Outline"
    url: /outline/
    
  - title: "Modeling"
  - title: "Basketball Stats Engineering"
    url: /basketball_stats_engineering/
  - title: "Feature Engineering"
    url: /feature_engineering/
  - title: "Modeling"
    url: /modeling/


  - title: "Results"
  - title: "Backtesting"
    url: /backtesting/
  - title: "2025 Predictions"
    url: /2025_predictions/

  - title: "Performance"
  - title: "Machine Learning Mania"
    url: /machine_learning_mania/
